# Generated by Django 5.1.3 on 2025-05-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_subsection_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subsection',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsection',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
